config/routes.rb
SampleApp::Application.routes.draw do
  resources :portfolios
  resources :videos
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    resources :portfolios
  end

  resources :users	
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/setup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/videos',  to: 'videos#index',         via: 'get'
  match '/portfolio', to: 'portfolios#show',     via: 'get'
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	belongs_to :user
	has_many :videos
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio,   only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user,  only: [:index, :new, :edit, :update, :destroy]
  before_action :admin_user,      only: [:new, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
    @users = User.where(admin: nil)
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @videos = @portfolio.videos
    @user = User.find(@portfolio.user_id)
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render action: 'show', status: :created, location: @portfolio }
      else
        format.html { render action: 'new' }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:feed, :cover_image, :bio, :user_id, :originally_from, :website,
                                        :phone_number, :video_reel_name, :video_reel_url, :fav_director,
                                        :fav_movie, :fav_book, :fav_quote, :fav_video_name, :fav_video_url,
                                        :position, :prev_clients, :skills, :short_goals, :long_goals, 
                                        :home_pic, :doing_now, :currently, :twitter, :youtube, :vimeo, 
                                        :video_reel_type, :fav_video_type)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if purpose == "create" %>

    <% @users_without_portfolios = User.includes(:portfolio).where(:portfolios => { :id => nil}) %>
    <% @user_array = @users_without_portfolios.where(admin: nil) %>

    <div class="form-group">
      <%= f.label "Whose Portfolio is this?" %>
      <%= f.select :user_id, options_from_collection_for_select(@user_array, "id", "name") %>
    </div> 

  <% end %>

  <div class="form-group">
    <%= f.label :cover_image, "Link to Portfolio Header Image" %>
    <%= f.text_field :cover_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :home_pic, "Link to Homepage Image" %>
    <%= f.text_field :home_pic, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label "Biography" %>
    <%= f.text_area :bio, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Originally From" %>
    <%= f.text_field :originally_from, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Link to Website" %>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Contact (Phone or Email)" %>
    <%= f.text_field :phone_number, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label "Name of your most recent Video Reel" %>
    <%= f.text_field :video_reel_name, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label "Vimeo number for your most recent Video Reel" %>
    <%= f.text_field :video_reel_url, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label "Who hosts this video?" %>
      <%= f.select :video_reel_type, options_for_select([['Vimeo', 'vimeo'], ['YouTube', 'youtube'], ['Direct Link', 'dir_link']], :selected => f.object.video_reel_type) %>
  </div> 
  <div class="form-group">
    <%= f.label "Favorite Director" %>
    <%= f.text_field :fav_director, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Favorite Movie" %>
    <%= f.text_field :fav_movie, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Favorite Book" %>
    <%= f.text_field :fav_book, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Favorite Quote" %>
    <%= f.text_field :fav_quote, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Name of your Favorite Music Video" %>
    <%= f.text_field :fav_video_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Link to your Favorite Music Video" %>
    <%= f.text_field :fav_video_url, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label "Who hosts this video?" %>
      <%= f.select :fav_video_type, options_for_select([['Vimeo', 'vimeo'], ['YouTube', 'youtube'], ['Direct Link', 'dir_link']], :selected => f.object.fav_video_type) %>
  </div> 
  <div class="form-group">
    <%= f.label "Preferred position on set" %>
    <%= f.text_field :position, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Previous clients" %>
    <%= f.text_field :prev_clients, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Skills" %>
    <%= f.text_field :skills, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Short-term Goals" %>
    <%= f.text_field :short_goals, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Long-term Goals" %>
    <%= f.text_field :long_goals, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "What you're doing now" %>
    <%= f.text_field :doing_now, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Currently" %>
    <%= f.text_field :currently, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "YouTube Link" %>
    <%= f.text_field :youtube, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Vimeo Link" %>
    <%= f.text_field :vimeo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Twitter Link" %>
    <%= f.text_field :twitter, class: "form-control" %>
  </div>
  <% if purpose == "create" %>
    <div class="actions">
     <%= f.submit "Create Portfolio", class: "btn btn-large btn-primary" %>
    </div>
  <% elsif purpose == "edit" %>
    <div class="actions">
     <%= f.submit "Update Portfolio", class: "btn btn-large btn-primary" %>
    </div>  
  <% end %> 

<% end %>

app/views/portfolios/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
  	<h1>Editing portfolio</h1>

<%= render 'form', :purpose => "edit" %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>
  </div>
</div>

app/views/portfolios/index.html.erb
<% provide(:title, "All Portfolios") %>


<div class="portfolio_index">
  <h1 class="portfolio_title">All Portfolios</h1>
  <h2 class="new_user"><%= link_to "Create New User", new_user_path %></h2>
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-md-6">
        <div class="user_name">
          <% if user.portfolio.nil? %>
            <%= user.name %> <%= user.last_name %>
            <% if current_user.admin? %>
              <div class="index_portfolio_link">
                <%= link_to "Edit User Settings", edit_user_path(user) %> | 
                <span class="create_portfolio_link"><%= link_to "Create New Portfolio", new_portfolio_path %></span>
              </div>
            <% end %>
          <% else %>
            <%= link_to (user_portfolio_path(user.id, user.portfolio.id)) do %>
              <%= user.name %> <%= user.last_name %>
              <div class="index_portfolio_link">
                <%= link_to "Edit User Settings", edit_user_path(user) %> | 
                <%= link_to "Edit Portfolio", edit_portfolio_path(user.portfolio.id) %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
<h1>New portfolio</h1>
<%= render 'form', :purpose => "create" %>
<%= link_to 'Back', portfolios_path %>
	</div>
</div>

app/views/portfolios/show.html.erb
<% provide(:title, @user.name) %>
<p id="notice"><%= notice %></p>


<script>
  $(document).ready(function() {
    var description = "This is a description";
    
    var populateVideo = function(video) {
       var type ="<div class='video'>" + video + "</div>";
      $('#contentThatFades').append(type);

            $(".video").fitVids();
            setTimeout(function(){
            $("#panelThatSlides").slideDown(400);
      }, 600);           
    }
    $('.videoLink').click(function () {
      //var videoVal = ($("#"+ eventID).data('video'));
      var sourceE = $(this).data('video');
      if ($("#panelThatSlides").is(":visible")) {
          
            
              $("#panelThatSlides").slideUp(400);
              setTimeout(function(){
                $('#contentThatFades').empty();
                populateVideo(sourceE);
              }, 400);
      }
      else {
        populateVideo(sourceE);
      }
    });
  });
    
  </script>

<div class="row">
  <div class="home_link col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= link_to "Home", root_path %></div>
  <div class="portfolio_head col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <%= @user.name %> <%= @user.last_name %>
  </div>
	<div class="cover_image col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<img src="<%= @portfolio.cover_image %>">
	</div>
</div>


<div class="row">
  <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-12 col-xs-12">
    <div class="portfolio_title">
      <center>Website:</center>
    </div>
    <div class="portfolio_content bio_content">
      <center><a href="<%= @portfolio.website %>"><%= @portfolio.website %></a></center>
    </div>
  </div>
  <div class="col-lg-5 col-md-4 col-sm-12 col-xs-12">
    <div class="portfolio_title">
      <center>Contact:</center>
    </div>
    <div class="portfolio_content bio_content">
      <center><%= @portfolio.phone_number %></center>
    </div>
  </div>
  <% unless @portfolio.bio == nil or @portfolio.bio.blank? %>
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      <div class="portfolio_title"><center>Bio:</center></div>
      <div class="portfolio_content bio_content">
        <%= @portfolio.bio %>
      </div>
    </div>
  <% end %>
</div>
</div>

<div id="panelThatSlides" style="display:none;background:#eee;padding:10px;">
<center>
  <div id="contentThatFades">
        
  </div>
</center>
</div>

<div class="container">
<div class="row">
  
  <% unless @portfolio.video_reel_url == nil or @portfolio.video_reel_url.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
      <div class="portfolio_title_smaller">
        Latest Video Reel:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">   
      <div class="portfolio_content bio_content">
        <% if @portfolio.video_reel_type == "vimeo" %>
          <span class="videoLink" data-video="<iframe src='http://player.vimeo.com/video/<%= @portfolio.video_reel_url %>?title=0&amp;byline=0&amp;portrait=0' width='400' height='225' frameborder='0'></iframe>"><%= @portfolio.video_reel_name %></span>
        <% end %>
        <% if @portfolio.video_reel_type == "youtube" %>
          <span class="videoLink" data-video="<iframe width='425' height='349' src=http://www.youtube.com/embed/<%= @portfolio.video_reel_url %> frameborder='0' allowfullscreen></iframe>"><%= @portfolio.video_reel_name %>
          </span>
        <% end %>
        <% if @portfolio.video_reel_type == "dir_link" %>
            <a href="<%= @portfolio.video_reel_url %>"><%= @portfolio.video_reel_name %></a>
        <% end %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.fav_video_url == nil or @portfolio.fav_video_url.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
      <div class="portfolio_title_smaller">
        Personal Work You're Most Proud of:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content red_link">
        <% if @portfolio.fav_video_type == "vimeo" %>
          <span class="videoLink" data-video="<iframe src='http://player.vimeo.com/video/<%= @portfolio.fav_video_url %>?title=0&amp;byline=0&amp;portrait=0' width='400' height='225' frameborder='0'></iframe>"><%= @portfolio.fav_video_name %></span>
        <% end %>
        <% if @portfolio.fav_video_type == "youtube" %>
          <span class="videoLink" data-video="<iframe width='425' height='349' src=http://www.youtube.com/embed/<%= @portfolio.fav_video_url %> frameborder='0' allowfullscreen></iframe>"><%= @portfolio.fav_video_name %>
          </span>
        <% end %>
        <% if @portfolio.fav_video_type == "dir_link" %>
            <a href="<%= @portfolio.fav_video_url %>"><%= @portfolio.fav_video_name %></a>
        <% end %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.originally_from == nil or @portfolio.originally_from.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <div class="portfolio_title_smaller">
        Originally From:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content from_content">
        <%= @portfolio.originally_from %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.fav_director == nil or @portfolio.fav_director.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Favorite Director(s):
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.fav_director %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.fav_movie == nil or @portfolio.fav_movie.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Favorite Movie:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.fav_movie %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.fav_book == nil or @portfolio.fav_book.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Favorite Book:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.fav_book %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.fav_quote == nil or @portfolio.fav_quote.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Favorite Quote:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.fav_quote %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.position == nil or @portfolio.position.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Preferred Position on Set:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.position %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.prev_clients == nil or @portfolio.prev_clients.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Previous Clients:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.prev_clients %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.skills == nil or @portfolio.skills.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Skills:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.skills %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.short_goals == nil or @portfolio.short_goals.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Short-term Goals:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.short_goals %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.long_goals == nil or @portfolio.long_goals.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Long-term Goals:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.long_goals %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.doing_now == nil or @portfolio.doing_now.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        What you are doing now:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.doing_now %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.currently == nil or @portfolio.currently.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Currently:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <%= @portfolio.currently %>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.vimeo == nil or @portfolio.vimeo.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Vimeo Page:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <a href="<%= @portfolio.vimeo %>"><%= @portfolio.vimeo %></a>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.youtube == nil or @portfolio.youtube.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        YouTube Page:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <a href="<%= @portfolio.youtube %>"><%= @portfolio.youtube %></a>
      </div>
    </div>
  <% end %>
  <% unless @portfolio.twitter == nil or @portfolio.twitter.blank? %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">    
      <div class="portfolio_title_smaller">
        Twitter Feed:
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">  
      <div class="portfolio_content bio_content">
        <a href="<%= @portfolio.twitter %>"><%= @portfolio.twitter %></a>
      </div>
    </div>
  <% end %>
</div>


<center>
	<% @videos.each do |video| %>
    <img class="videoLink" data-video="<%= video.url %>" src="<%= video.cover %>">
  <% end %>
</center>


<% if signed_in? %>
  <% if current_user.admin?  %>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> 
      <center>
        <%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
        <%= link_to 'Back', portfolios_path %>
      </center>
    </div>
  <% end %>
<% end %>