config/routes.rb
SampleApp::Application.routes.draw do
  resources :portfolios
  resources :videos
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    resources :portfolios
  end

  resources :users	
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/setup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/videos',  to: 'videos#index',         via: 'get'
  match '/portfolio', to: 'portfolios#show',     via: 'get'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <strong>
  </strong>
</footer>

app/views/layouts/_header.html.erb
<% if signed_in? %>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">  
   <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">Thunderdome</div>
    </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Portfolios", portfolios_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings",  edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
                </li>
                 </ul>         
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>